---
# we can't have deps on handlers without running the complete role, so just duplicate them :(

- name: reload php
  service: name=php5-fpm state=reloaded enabled=yes

- name: reload apache2
  service: name=apache2 state=reloaded enabled=yes

- name: restart solr-jetty
  service: name=jetty state=restarted enabled=yes

- name: restart solr-jetty8
  service: name=jetty8 state=restarted enabled=yes

- name: reload ufw
  ufw: state=reloaded
