---
- name: install ntp
  apt: name=ntp state=installed

- template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: allow udp outbound ports
  ufw: rule=allow interface={{ public_interface }} direction=out proto=udp to_port=123
  notify: reload ufw

