---
- name: put vhost ssl request template
  template: src=request-vhost.sh dest=/root/ssl/request-{{ item.url }}.sh owner=root group=root mode=0700
  with_items: "{{ vhosts }}"
  when: not item.delete|default(False)
  tags: ['vhosts', 'letsencrypt']
