---
- name: create user {{ item.name }}
  user: name={{ item.name }} shell=/bin/bash
  with_items: "{{ systemusers }}"

- name: put public key for {{ item.name }}
  authorized_key: user={{ item.name }} key="{{ item.sshkeys|join('\n') }}" state=present
  with_items: "{{ systemusers }}"

- name: grant {{ item.name }} sudo
  lineinfile: "dest=/etc/sudoers.d/fiaasco regexp='^{{ item.name }}' line='{{ item.name }}        ALL = NOPASSWD: ALL' state=present create=yes mode=0440"
  with_items: "{{ systemusers }}"

- name: create group for developers
  group: name=developers

- name: create group for customers
  group: name=customers

- name: create group for ftpusers
  group: name=ftpusers

- name: put developers sudoers
  template: src=sudo-devs.j2 dest=/etc/sudoers.d/developers owner=root group=root mode=0440 validate='visudo -cf %s'
