---
- name: remove deleted vhost ssl request script
  file: path=/root/ssl/request-{{ item.url }}.sh state=absent
  with_items: "{{ vhosts }}"
  when: item.delete|default(False)
  tags: ['vhosts', 'letsencrypt']

# TODO: we also have to make sure acme.sh cron doesn't try to renew a removed vhost cert
