---
- name: add repo for custom packages
  apt_repository: repo="deb http://repo.werus.be/apt/debian {{ ansible_distribution_release }} main" state=present update_cache=yes

- name: Install PECL dependencies
  apt: name=php-pear state=present cache_valid_time=3600 update_cache=yes

# install 

- include: pecl.yml package={{ php_pecl_extra_extensions }}
