---
- name: enable Apache munin plugins
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - apache_accesses
    - apache_processes
    - apache_volume
  notify: restart munin-node

- name: place external checks for apache and its vhosts
  template: src=apache/vhosts.conf.j2 dest=/etc/icinga2/conf.d/vhosts.conf mode=0644
  notify: restart icinga2 and update master config
  when: "'test' not in inventory_hostname"

- name: adapt munin-config for apache
  template: src=apache/munin-conf.j2 dest=/etc/munin/plugin-conf.d/apache mode=0644
  notify: restart munin-node
