- name: place icinga2 checks for attic
  template: src=backup/{{ item }}.j2 dest=/etc/icinga2/conf.d/{{ item }} owner=root group=root mode=0755
  with_items:
    - attic-backup.conf
  notify: restart icinga2 and update master config
