---
# SUSPENDED: we have to rethink this check
#- name: place check_mk script for memcached
#  template: src=memcached/check_memcached.j2 dest=/usr/lib/check_mk_agent/local/check_memcached mode=0755 owner=root group=root
#  notify: inventory the new host

- name: put memcached check
  template: src=memcached/memcached.conf.j2 dest=/etc/icinga2/conf.d/memcached.conf mode=0644
  notify: restart icinga2 and update master config

- name: enable memcached munin plugins
  file: src=/usr/share/munin/plugins/memcached_ dest=/etc/munin/plugins/memcached_{{ item }} state=link
  with_items:
    - rates
    - bytes
    - counters
  notify: restart munin-node
