---
- name: enable Mysql munin plugins
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - mysql_bytes
    - mysql_queries
    - mysql_slowqueries
    - mysql_threads
  notify: restart munin-node

- name: grant usage for monitor user
  mysql_user: name={{ monitor_mysql.user }} password={{ monitor_mysql.pass }} priv=*.*:USAGE state=present append_privs=yes

- name: place icinga2 checks for mysql
  template: src=mysql/{{ item }}.j2 dest=/etc/icinga2/conf.d/{{ item }} owner=root group=root mode=0755
  with_items:
    - mysql.conf
    - automysqlbackup.conf
  notify: restart icinga2 and update master config
