---
- name: enable postfix munin plugins
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - postfix_mailqueue
    - postfix_mailvolume
  notify: restart munin-node

- name: place external checks for apache and its vhosts
  template: src=postfix/mailq.conf.j2 dest=/etc/icinga2/conf.d/mailq.conf mode=0644
  notify: restart icinga2 and update master config
