---
- name: remove cmk packages
  apt: name={{ item }} state=absent cache_valid_time=3600 update_cache=yes
  with_items:
    - check-mk-config-icinga
    - check-mk-server
    - check-mk-agent
    - xinetd

- name: remove unused config files accesses
  file: path=/etc/xinetd.d/check_mk state=absent
  with_items:
    - /etc/xinetd.d/check_mk
    - /etc/check_mk

- name: remove default configdir
  file: path=/etc/check_mk state=absent
