---
monitor_varnish:
  - name: cache_hit_percent
    warn: 70
    crit: 80
  - name: cache_miss
    warn: 50
    crit: 90

monitor_mysql:
  checks:
    - open-files
    - slow-queries
    - connection-time
  user: monitor
  pass: monitor
