---
# Losely based on http://allanfeid.com/content/creating-chroot-jail-ssh-access
# Custom l2chroot

- name: install required tools for backup
  apt: name={{ item }} state=latest
  with_items:
    - libacl1-dev
    - libssl-dev
    - python3-pip
    - python-virtualenv

- name: install attic
  pip: name=attic executable={{ pip_exec }}

- name: create group for backup-users
  group: name={{ server_backup_group }}

- include: backup-jail.yml

- template: src=sshd.config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644 
  register: sshconfig

- name: restart ssh now
  service: name=ssh state=restarted
  when: sshconfig.changed

- name: place cronjob for munin-monitoring
  cron: name="munin-du" minute=18 job="du -sk {{ server_backup_dir }}/home/* > /tmp/munin-du_multidirs.cache"

- name: place munin-script
  copy: src=munin/du_multidirs dest=/etc/munin/plugins/du_multidirs owner=root group=root mode=0755
  notify: restart munin-node
