---
- name: enable non free repos for fastcgi
  apt_repository: repo='{{ item }}' state=present update_cache=no
  with_items:
    - 'deb http://ftp.debian.org/debian wheezy non-free'
    - 'deb-src http://ftp.debian.org/debian wheezy non-free'
    - 'deb http://security.debian.org/ wheezy/updates non-free'
    - 'deb-src http://security.debian.org/ wheezy/updates non-free'
    - 'deb http://ftp.debian.org/debian wheezy-updates non-free'
    - 'deb-src http://ftp.debian.org/debian wheezy-updates non-free'
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"
  register: newrepos

- apt: update_cache=yes
  when: newrepos.changed

- name: install fastcgi
  apt: name=libapache2-mod-fastcgi state=installed cache_valid_time=3600 update_cache=yes

- name: Apache | Enable fastcgi
  apache2_module: name=fastcgi state=present
  notify: reload apache2

- name: configure fastcgi for php-fpm
  template: src=fastcgi.conf.j2 dest=/etc/apache2/mods-available/fastcgi.conf
  notify: reload apache2

